stages:
  - test


test:
  image: docker:20-git
  services:
    - docker:20-dind
  variables:
    TABLE_NAME: "Pipeline_test"
    DOCKER_TLS_CERTS: "/certs"
    CITY: "Barlinek"
    PATH: $(cd $PROJECT_PATH)
  before_script:
    - $PATH
  script:
    - env
    - docker-compose up &