stages:
  - test


variables:
  TABLE_NAME: "Pipeline_test"
  DOCKER_TLS_CERTS: "/certs"
  DOCKER_HOST: tcp://localhost:2375


test:
  image: docker:20-git
  services:
    - docker:20-dind
  before_script:
    - docker info
  script:
    - sudo docker cp -r VAGRANT_CREDS:/home/vagrant/MY_PROJECT/GITLAB_DOCKERIZE_APPLICATION/Dockerize_Weather_application/ .
    - cd /home/vagrant/MY_PROJECT/GITLAB_DOCKERIZE_APPLICATION/Dockerize_Weather_application/Grafana_Prometheus/
    - docker-compose up