stages:
  - weather_app
  - delete_weather_app

weather_app:
  image: docker:20-git
  services:
    - docker:20-dind
  variables:
    DOCKER_TLS_CERTS: "/certs"
  script:
    - cd /home/vagrant/MY_PROJECT/GITLAB_DOCKERIZE_APPLICATION/Dockerize_Weather_application/Grafana_Prometheus/
    - docker-compose up &
delete_weather_app:
  script:
    - docker-compose down