weather_app:
  variables:
    TABLE_NAME: "Pipeline_test"
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - cd /home/vagrant/MY_PROJECT/GITLAB_DOCKERIZE_APPLICATION/Dockerize_Weather_application/Grafana_Prometheus
    - export TABLE_NAME=$TABLE_NAME
    - docker-compose up