variables:
  COMPOSE_FILE: ./Grafana_Prometheus/docker-compose.yml

stages:
  - build
  - deploy
  - delete

app:
  stage: build
  script: docker build -f ./weather_app/Dockerfile .

db:
  stage: build
  script: docker build -f ./mysql_database/Dockerfile .

deploy_weather_app:
  stage: deploy
  image: docker:20-git
  services:
    - docker:20-dind
  variables:
    DOCKER_TLS_CERTS: "/certs"
  script:
    - ls
    - docker-compose up -d


delete_weather_app:
  stage: delete
  script:
    - ls
    - docker-compose down
  when: manual
