stages:
  - test


test:
  image: docker:20-git
  services:
    - docker:20-dind
  variables:
    TABLE_NAME: "Pipeline_test"
    DOCKER_TLS_CERTS: "/certs"
    CITY: "Barlinek"
  before_script:
    - export PATH=$PROJECT_PATH
  script:
    - cd $PATH
    - env
    - docker-compose up &